### ISSUE TITLE
Not working properly for me

### ISSUE THREAD

**Issue by STashakkori** [TheThirdOne/elf-edit#11]
Hello I currently run this on a 64-bit elf and notice that I can't navigate the file at all unless I hit '9' which allows me to traverse one character at a time. Seems not right

Also I don't get to see the whole file, just the beginning. Get this at the end of every file which doesn't seem correct:

Error parsing. Program header outside file.

Please assist. Thank you

**Comment by TheThirdOne** [comment]
I don't know what your issue is. I have not run into any issues with it myself except when accidentally running it on a 32bit file. I would need additional information to actually find out what the issue is such as how are you actually running elf-edit, what is your operating system, etc.

It works for me on Arch Linux when built using cargo. Changing OS / how its run may fix your issue.

I will not be fixing this because I would rather put my time into other things.

If you want to try to fix this, some of the behavior you mentioned is defined by these snippets:

https://github.com/TheThirdOne/elf-edit/blob/bbb30640986b645ae5bc6386897c35265ce32819/src/main.rs#L62-L74

https://github.com/TheThirdOne/elf-edit/blob/bbb30640986b645ae5bc6386897c35265ce32819/src/main.rs#L130-L132
